# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "virtio_pci" "floppy" "sr_mod" "virtio_blk" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a0041d4a-5f1c-48f8-ae27-b9799f0cd66c";
      fsType = "ext4";
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/6b52b3d7-a9f2-446f-b186-6236593cc225";
      fsType = "ext4";
    };

  fileSystems."/var/lib/nixos-containers/omas/var/lib" =
    { device = "/dev/disk/by-uuid/3e437349-57fe-47cc-97ad-0636c555a467";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/b9319cb7-8297-43ef-845b-d3f04f6b0ed1"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  nix.settings.max-jobs = lib.mkDefault 2;
}
