# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "pcie_rockchip_host" "phy_rockchip_pcie" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/6d9b0e4a-98ca-4eba-b1b5-a0d936dea91a";
      fsType = "ext4";
    };

  fileSystems."/debian" =
    { device = "/dev/disk/by-uuid/04dc6fc7-f3c7-49bb-8e3b-f23aa1f75a05";
      fsType = "ext4";
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/9d24eb43-9737-4ad8-b819-d99cdf92c53f";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/a2d20031-d197-4260-a2b8-58854d71058f"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";
}
