# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/af29a10c-67e3-48ad-9322-88def8c1c078";

  fileSystems."/" =
    { device = "/dev/vg1/nixos-root";
      fsType = "xfs";
    };

  fileSystems."/nix/store" =
    { device = "/dev/vg1/nixos-store";
      fsType = "xfs";
    };
  
#  fileSystems."/home/gos/data" =
#    { device = "/dev/vg1/gos";
#      fsType = "xfs";
#    };

  fileSystems."/home/gos/data2" =
    { device = "/dev/disk/by-uuid/3c5c8228-56d7-42f6-92d1-c0437bf66447";
      fsType = "btrfs";
      options = [ "ssd" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9FB9-1E18";
      fsType = "vfat";
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
